# Boxlet configuration file

# Environment
environment: development
debug: true

# File system parameters
# path: ./
# upload_dir ./uploads
# tmp_dir /tmp
file_system_root: /

# Server type and listen parameters
port: 8077
host: localhost
server_type: thin
daemonize: false

# Database config
db:
  development:
    host: localhost
    db: boxlet_dev
  production:
    host: localhost
    # port:
    # user:
    # pass:
    db: boxlet
