# Boxlet configuration file

port: 8077
host: localhost
server_type: thin
environment: development
# daemonize: true
debug: true
# path: ./
# upload_dir ./uploads
# tmp_dir /tmp
file_system_root: /

db:
  development:
    host: localhost
    db: boxlet_dev
  production:
    host: localhost
    # port:
    # user:
    # pass:
    db: boxlet
