# Boxlet configuration file

# Environment
environment: development
debug: false

# File system parameters
# path: ./
# upload_dir: ./uploads
# tmp_dir: /tmp
# file_system_root: /

# Capacity is either a percentage of available space on the drive or number in MB
capacity: 90%

# Server type and listen parameters
port: 8077
host: localhost
server_type: thin
daemonize: false
pid_file: server.pid
log_file: server.log

#use s3
s3:
  enabled: false
  access_key_id:
  secret_access_key:
  bucket: boxlet

# Database config
db:
  development:
    host: localhost
    db: boxlet_dev
  production:
    host: localhost
    # port:
    # user:
    # pass:
    db: boxlet
