# Boxlet configuration file

# TCP Debug mode changes logging level between WARN (false) and DEBUG (true)
# tcp_debug: true

# Server configuration
# tcp_listen_ip: 127.0.0.1
# tcp_listen_port: 8077
# server_handler: thin


port: 8077
host: localhost
server_type: thin
environment: development
# daemonize
debug: true
# path
# upload_dir
# tmp_dir
file_system_root: /

db:
  development:
    host: localhost
    db: boxlet_dev
  production:
    host: localhost
    # port:
    # user:
    # pass:
    db: boxlet
